### ISSUE TITLE
[BUG] Template parsing error for START OBJECT

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-ai-flow-framework#116]
### What is the bug?
When invoking workflow API for Create Connector Step, the template parser fails.

```
java.lang.IllegalStateException: Can't get text on a START_OBJECT at 1:607
        at org.opensearch.common.xcontent.json.JsonXContentParser.text(JsonXContentParser.java:99) ~[opensearch-x-content-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.flowframework.common.TemplateUtil.parseStringToStringMap(TemplateUtil.java:76) ~[?:?]
        at org.opensearch.flowframework.model.WorkflowNode.parse(WorkflowNode.java:144) ~[?:?]
        at org.opensearch.flowframework.model.Workflow.parse(Workflow.java:107) ~[?:?]
        at org.opensearch.flowframework.model.Template.parse(Template.java:167) ~[?:?]
        at org.opensearch.flowframework.model.Template.parse(Template.java:195) ~[?:?]
        at org.opensearch.flowframework.rest.RestCreateWorkflowAction.prepareRequest(RestCreateWorkflowAction.java:58) ~[?:?]
        at org.opensearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:106) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.security.filter.SecurityRestFilter.lambda$wrap$0(SecurityRestFilter.java:141) ~[?:?]
        at org.opensearch.rest.RestController.dispatchRequest(RestController.java:323) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.rest.RestController.tryAllHandlers(RestController.java:414) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.rest.RestController.dispatchRequest(RestController.java:252) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.security.ssl.http.netty.ValidatingDispatcher.dispatchRequest(ValidatingDispatcher.java:68) [opensearch-security-3.0.0.0-SNAPSHOT.jar:3.0.0.0-SNAPSHOT]
        at org.opensearch.http.AbstractHttpServerTransport.dispatchRequest(AbstractHttpServerTransport.java:365) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.http.AbstractHttpServerTransport.handleIncomingRequest(AbstractHttpServerTransport.java:444) [opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
```

### How can one reproduce the bug?
Invoke the API:

```
curl -XPOST --insecure -u 'admin:admin' -H "Content-Type: application/json" 'https://localhost:9200/_plugins/_flow_framework/workflow' -d '{
  "name": "deploy-register-model",
  "description": "test case",
  "use_case": "SEMANTIC_SEARCH",
  "version": {
    "template": "1.0.0",
    "compatibility": [
      "2.12.0",
      "3.0.0"
    ]
  },
  "workflows": {
    "provision": {
      "nodes": [
        {
          "id": "workflow_step_1",
          "type": "create_connector",
          "inputs": {
            "name": "OpenAI Chat Connector",
            "description": "The connector to public OpenAI model service for GPT 3.5",
            "version": "1",
            "protocol": "http",
            "parameters": {
              "endpoint": "api.openai.com",
              "model": "gpt-3.5-turbo"
            },
            "credential": {
              "openAI_key": "..."
            },
            "actions": [
              {
                "action_type": "predict",
                "method": "POST",
                "url": "https://${parameters.endpoint}/v1/chat/completions",
                "headers": {
                  "Authorization": "Bearer ${credential.openAI_key}"
                },
                "request_body": "{ \"model\": \"${parameters.model}\", \"messages\": ${parameters.messages} }"
              }
            ]
          }
        },
        {
          "id": "workflow_step_2",
          "type": "deploy_model",
          "inputs": {
            "model_id": {}
          }
        }
      ],
      "edges": [
        {
          "source": "workflow_step_1",
          "dest": "workflow_step_2"
        }
      ]
    }
  }
}'
```

### What is the expected behavior?
API should return a workflow ID

### What is your host/environment?
ubuntu

**Comment by dbwiddis** [comment]
Parsing fails on the value for this key:
```json
  "headers": {
    "Authorization": "Bearer ${credential.openAI_key}"
  }
```

**Comment by dbwiddis** [comment]
> at org.opensearch.flowframework.common.TemplateUtil.parseStringToStringMap(TemplateUtil.java:76) ~[?:?]
> at org.opensearch.flowframework.model.WorkflowNode.parse(WorkflowNode.java:144) ~[?:?]

The assumption made by the parser is that `input-fields` values inside an array are a string-to-string map unless specifically parsed otherwise, such as the `processors` field:
https://github.com/opensearch-project/opensearch-ai-flow-framework/blob/6ee3d5323a4ca2d8bbfc87fea271d8a4cbfe479f/src/main/java/org/opensearch/flowframework/model/WorkflowNode.java#L134-L148

In the JSON payload above, `headers` value is not a string, resulting in the failure:
```json
"actions": [
  {
    "action_type": "predict",
    "method": "POST",
    "url": "https://${parameters.endpoint}/v1/chat/completions",
    "headers": {
      "Authorization": "Bearer ${credential.openAI_key}"
    },
    "request_body": "{ \"model\": \"${parameters.model}\", \"messages\": ${parameters.messages} }"
  }
]
```

Proposed solution: special parsing for `headers` field similar to how `processors` are handled.  Note the headers values are a list of strings for each key, so the headers section should probably be
```json
"headers": {
  "Authorization": ["Bearer ${credential.openAI_key}"]
},
```

**Comment by owaiskazi19** [comment]
Without the `headers` the above request fails with the below

```
{"error":{"root_cause":[{"type":"flow_framework_exception","reason":"failed to parse field [workflows] of type [text] in document with id '8lrubIsBJZIDh7XL5w_D'. Preview of field's value: '{provision={nodes=[{inputs={protocol=http, credential={openAI_key=...}, name=OpenAI Chat Connector, description=The connector to public OpenAI model service for GPT 3.5, parameters={endpoint=api.openai.com, model=gpt-3.5-turbo}, actions=[{method=POST, request_body={ \"model\": \"${parameters.model}\", \"messages\": ${parameters.messages} }, action_type=predict, url=https://${parameters.endpoint}/v1/chat/completions}], version=1}, id=workflow_step_1, type=create_connector}, {inputs={model_id={}}, id=workflow_step_2, type=deploy_model}], edges=[{source=workflow_step_1, dest=workflow_step_2}], user_params={}}}'"}],"type":"flow_framework_exception","reason":"failed to parse field [workflows] of type [text] in document with id '8lrubIsBJZIDh7XL5w_D'. Preview of field's value: '{provision={nodes=[{inputs={protocol=http, credential={openAI_key=...}, name=OpenAI Chat Connector, description=The connector to public OpenAI model service for GPT 3.5, parameters={endpoint=api.openai.com, model=gpt-3.5-turbo}, actions=[{method=POST, request_body={ \"model\": \"${parameters.model}\", \"messages\": ${parameters.messages} }, action_type=predict, url=https://${parameters.endpoint}/v1/chat/completions}], version=1}, id=workflow_step_1, type=create_connector}, {inputs={model_id={}}, id=workflow_step_2, type=deploy_model}], edges=[{source=workflow_step_1, dest=workflow_step_2}], user_params={}}}'"},"status":500}

**Comment by owaiskazi19** [comment]
This is the request body. That was from the logs.

```
curl -XPOST --insecure -u 'admin:admin' -H "Content-Type: application/json" 'https://localhost:9200/_plugins/_flow_framework/workflow' -d '{"name":"deploy-register-model","description":"test case","use_case":"SEMANTIC_SEARCH","version":{"template":"1.0.0","compatibility":["2.12.0","3.0.0"]},"workflows":{"provision":{"nodes":[{"id":"workflow_step_1","type":"create_connector","inputs":{"name":"OpenAI Chat Connector","description":"The connector to public OpenAI model service for GPT 3.5","version":"1","protocol":"http","parameters":{"endpoint":"api.openai.com","model":"gpt-3.5-turbo"},"credential":{"openAI_key":"..."},"actions":[{"action_type":"predict","method":"POST","url":"https://${parameters.endpoint}/v1/chat/completions","request_body":"{ \"model\": \"${parameters.model}\", \"messages\": ${parameters.messages} }"}]}},{"id":"workflow_step_2","type":"deploy_model","inputs":{"model_id":{}}}],"edges":[{"source":"workflow_step_1","dest":"workflow_step_2"}]}}}'

**Comment by dbwiddis** [comment]
Right, same question. 

If you remove the request body does the error go away?  Isolate what is not parsing.

**Comment by dbwiddis** [comment]
One of these things is not like the other.
```
"request_body": "{ 
  \"model\": \"${parameters.model}\",
  \"messages\": ${parameters.messages}
}"
```

**Comment by owaiskazi19** [comment]
Worked without request body.

**Comment by owaiskazi19** [comment]
I am not facing the parsing issue after a clean install of the cluster with the plugin. I'll go ahead and close this issue for now.
