### ISSUE TITLE
[BUG] org.opensearch.flowframework.FlowFrameworkPluginIT.testPluginInstalled test is failing on Windows CI

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-ai-flow-framework#87]
### What is the bug?
```
org.opensearch.flowframework.FlowFrameworkPluginIT > testPluginInstalled FAILED

    org.opensearch.client.ResponseException: method [GET], host [http://0.0.0.0:0/], URI [/_cat/plugins], status line [HTTP/1.1 404 Not Found]

        at __randomizedtesting.SeedInfo.seed([FEE4D7C34DADF2E3:F643B94C26B8D07D]:0)
Suite: Test class org.opensearch.flowframework.FlowFrameworkPluginIT
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:376)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:346)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:321)
        at app//org.opensearch.flowframework.FlowFrameworkPluginIT.testPluginInstalled(FlowFrameworkPluginIT.java:34)
  1> [2023-10-12T13:17:21,342][INFO ][o.o.f.FlowFrameworkPluginIT] [testPluginInstalled] before test
```

### How can one reproduce the bug?
```

REPRODUCE WITH: gradlew ':integTest' --tests "org.opensearch.flowframework.FlowFrameworkPluginIT.testPluginInstalled" -Dtests.seed=FEE4D7C34DADF2E3 -Dtests.security.manager=false -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=en-AU -Dtests.timezone=America/Mexico_City -Druntime.java=17
```

### What is the expected behavior?
Test should pass

### What is your host/environment?
Windows

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by dbwiddis** [comment]
See [here](https://github.com/opensearch-project/geospatial/blob/059b10da7b9cc6cc9035c7ce8dba1f93955851f4/build.gradle#L203-L207) for something possibly similar. Can we try it as a fix?
```groovy
integTest {
    // ...
    doFirst {
        // ...
        // There seems to be an issue when running multi node run or integ tasks with unicast_hosts
        // not being written, the waitForAllConditions ensures it's written
        getClusters().forEach { cluster ->
            cluster.waitForAllConditions()
        }
    }
}
```
